---
title: "Tester"
format: html
editor: visual
---

```{r}

library(quantmod)
library(tidyquant)
library(RTL)
library(tidyverse)


treasury_symbols <- c(
  "1-Month"  = "DGS1MO",
  "3-Month"  = "DGS3MO",
  "6-Month"  = "DGS6MO",
  "1-Year"   = "DGS1",
  "2-Year"   = "DGS2",
  "3-Year"   = "DGS3",
  "5-Year"   = "DGS5",
  "7-Year"   = "DGS7",
  "10-Year"  = "DGS10",
  "20-Year"  = "DGS20",
  "30-Year"  = "DGS30")




tester <- tidyquant::tq_get(treasury_symbols[1],
                  get = "economic.data",
                  from = "2026-01-01")


tester$price %>% tail(1)


```

```{r}

init_new <- function(start, end, coupon, periodocity, FV, quantity){
  
  T2M <- as.numeric(as_date(end)) - as.numeric(as_date(Sys.Date()))
  
  years <- (as.numeric(as_date(end)) - as.numeric(as_date(start)))/365
  
  temp_build <- tibble::tibble(length = years,
                               coupon_rate = coupon,
                               TTM = T2M,
                               N = periodocity,
                               Face_Value = FV,
                               Quantity = quantity,
                               Nominal_Value = quantity*FV)
  
  temp_build
  
}

test_table <- init_new(0,0,0,0,0,0)


```

```{r}


test_list <- c(1,2,3,4,5)

test_cat <- cat(test_list, sep = ", ")

print(cat(paste(test_list)))

test_cat


paste("Rows", paste(test_list, collapse = ", "), "Will be Deleted")


```

```{r}

update_portfolios <- function(){

port_path <- paste(dirname(getActiveDocumentContext()$path), "/Portfolios", sep = "") 
#This means the 'Portfolios' folder must live BESIDE the global file


portfolio_list <- list.files(path = port_path, pattern = "\\.csv$")

portfolio_paths <- lapply(portfolio_list, function(x) paste0(port_path,"/", x, sep = ""))

portfolio_files <- lapply(portfolio_paths, read.csv, check.names = FALSE)
#So from this I learnt that the csv file needs to have something in it for this entire function to work
#Two solutions - require at least one row of info or reduce fragility in the case of one or two NAs

names(portfolio_files) <- portfolio_list

portfolio_files

}




portfolio_files <- update_portfolios()

portfolio_list <- names(portfolio_files)

lapply(portfolio_list, function(x){gsub(".csv", "", x)})
```

```{r}


names(test_table)



```

```{r}


test_tibble <- tibble::tibble(start = c("2026-01-01", "2026-02-01"),
                              end = c("2026-02-01", "2026-03-01"),
                              purchase_price = c(100,200),
                               length = c(0.25,0.5),
                               coupon_rate = c(0.5, 0.01),
                               N = 2,
                               Face_Value = 100,
                               Quantity = c(5,50)
                              )

test_tibble <- test_tibble %>% 
  dplyr::mutate(bond_id = row_number())

test_tibble %>%
  dplyr::group_by(bond_id) %>% 
  dplyr::reframe(Date = seq.Date(from = as.Date(start), to = as.Date(end), by = "day")) %>% 
  dplyr::left_join(test_tibble, by = join_by(bond_id)) %>% 
  dplyr::mutate(TTM = get_bond_ttm(Date, as.Date(end)))




```

```{r}

setup_yield_table <- function(df){
  
  df %>% 
    rowwise() %>% 
    dplyr::mutate(bond_id = row_number()) %>%
    dplyr::group_by(bond_id) %>% 
    tidyr::expand(bond_id, seq.Date(from = start, to = end, by = "day"))
    

}

get_bond_ttm <- function(settlement_date, maturity_date) {
  # settlement_date: date of bond ownership transfer
  # maturity_date: maturity date of bond
  ttm <- as.numeric(difftime(maturity_date, settlement_date, units = "days")) / 365
  
  return(ttm)
}

setup_yield_table <- function(df){

df <- df %>% 
  dplyr::mutate(bond_id = row_number())

df %>%
  dplyr::group_by(bond_id) %>% 
  dplyr::reframe(Date = seq.Date(from = as.Date(start), to = as.Date(end), by = "day")) %>% 
  dplyr::left_join(test_tibble, by = join_by(bond_id)) %>% 
  dplyr::mutate(TTM = get_bond_ttm(Date, as.Date(end)))
  
}


setup_yield_table(test_tibble)




```
